### ISSUE TITLE
new Position() crashes in release mode

### ISSUE THREAD

**Issue by higher-faster-better** [jamesmontemagno/GeolocatorPlugin#173]
Version Number of Plugin: 4.1.2
Device Tested On: Huawei
Version of VS: VS 2017 for MAC
Version of Xamarin: Xamarin.IOS 11.2.0.11, Xamarin.Android 8.0.0.33

### Expected Behavior
create new position based new latitude and logitude

### Actual Behavior
new Position() works in debug mode but crashes in release mode

### Code snippet
var positiion = new Position(latitude, longitude);

The app crashes in release mode with above code.
Please help me to fix.

Thanks.

**Comment by higher-faster-better** [comment]
Sorry. This is wrong.

**Comment by higher-faster-better** [comment]
I thought I was wrong but I am really facing this problem in my project.
Any idea why it happens? IOS is ok, only Android is problem.

**Comment by higher-faster-better** [comment]
FATAL EXCEPTION: main
                                                   Process: com.ibase.mtwpublicapp, PID: 18460
                                                   android.runtime.JavaProxyThrowable: System.MissingMethodException: Method 'Plugin.Geolocator.Abstractions.Position..ctor' not found.
                                                     at MtwPublicApp.ViewModels.ResidentHome.Views.MyPlaceViewViewModel.set_HomeProfile (MtwPublicApp.Models.HomeProfile value) [0x00013] in <9e36ba5c62814b48bebbecffe0659b4a>:0 
                                                     at MtwPublicApp.Pages.ResidentHome.Views.MyPlaceView.SetHomeProfile (MtwPublicApp.Models.HomeProfile homeProfile) [0x00000] in <9e36ba5c62814b48bebbecffe0659b4a>:0 
                                                     at MtwPublicApp.Pages.ResidentHome.HomePage.OnDataSyncFailed (System.Object sender, System.Boolean isFailed) [0x00046] in <9e36ba5c62814b48bebbecffe0659b4a>:0 
                                                     at MtwPublicApp.ViewModels.ResidentHome.HomeViewModel+<GetHomeProfile>d__61.MoveNext () [0x000bf] in <9e36ba5c62814b48bebbecffe0659b4a>:0 
                                                   --- End of stack trace from previous location where exception was thrown ---
                                                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
                                                     at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
                                                     at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <c82a099136944d8aa96281cf061cbc12>:0 
                                                     at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <c82a099136944d8aa96281cf061cbc12>:0 
                                                     at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <c82a099136944d8aa96281cf061cbc12>:0 
                                                       at (wrapper dynamic-method) System.Object:442a8b96-e4f7-4820-b574-f1345908345d (intptr,intptr)
                                                       at mono.java.lang.RunnableImplementor.n_run(Native Method)
                                                       at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
                                                       at android.os.Handler.handleCallback(Handler.java:743)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:150)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by jamesmontemagno** [comment]
Most likely it is being linked out if you have it set to ALL (which i never do)

You can create a new position inside your Android project and then it wont be linked out..

Or just do a link skip:
Plugin.Geolocator.Abstractions;Plugin.Geolocator;

https://developer.xamarin.com/guides/android/advanced_topics/linking/

**Comment by higher-faster-better** [comment]
Link behavior is Don't Link for both debug and release in Android project.
The app works good in debug mode but failed to create new position in release mode.
It's still link problem?

**Comment by jamesmontemagno** [comment]
Check your link because it should never be Don't Link as it would include all of .NET into your app..

If it works in one and not the other it isn't the libraries fault. I recommend the link settings I showed.

Also not sure cause https://github.com/jamesmontemagno/GeolocatorPlugin/blob/master/src/Geolocator.Plugin.Abstractions/Position.cs#L9 looks prefect to me :)

**Comment by higher-faster-better** [comment]
I think I got this error after I updated package.
