### ISSUE TITLE
UWP. Doesn't detects correct if geolocation diabled globally.

### ISSUE THREAD

**Issue by ydanila** [jamesmontemagno/GeolocatorPlugin#191]
How to reproduce?

You need Win10 and UWP app.

Disable "Location for this device" via settings. Check.

`IsGeolocationAvailable = CrossGeolocator.IsSupported
				&& await CrossGeolocator.Current.GetIsGeolocationEnabledAsync()
				&& await CrossGeolocator.Current.GetIsGeolocationAvailableAsync();`

The result will be true. But if you try to get location via 

`var pos = await CrossGeolocator.Current.GetPositionAsync();`

You will get exception.

> {Plugin.Geolocator.Abstractions.GeolocationException: A geolocation error occured: Unauthorized
   at Plugin.Geolocator.GeolocatorImplementation.<CheckPermissionAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Plugin.Geolocator.GeolocatorImplementation.<GetPositionAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MyApp.ViewModels.Map.MapViewModel.<HandleAppearing>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MyApp.Views.MapPage.<OnAppearing>d__3.MoveNext()}

**Comment by prashantvc** [comment]
This looks like a bug. Could you make sure that you set the `ID_CAP_LOCATION` permission.
I don't see `GetIsGeolocationEnabledAsync` in the latest plugin.
Could you provide the following details? It will help us to troubleshoot the issue

## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

**Comment by ydanila** [comment]
Version: 5.0.0.175-beta
Device: Win 10 x64 1709 Build 16299.125
Testested on Local PC
Version of VS: 2017 15.5.1
Xamarin version: 4.8.0.753
Xamarin Forms version: 2.5.0.91635
Microsoft.NETCore.UniversalWindowsPlatform: 5.4.0

Of course it has ID_CAP_LOCATION permission and starts to work as "Location for this device" set to On and throws exception as it will be set to Off.

**Comment by jamesmontemagno** [comment]
It is impossible to detect this, I already tried. UWP doesn't give the APIs needed sorry.

**Comment by ydanila** [comment]
As it impossible to detect, could be used workaround like this.

> var geolocationAvailable = CrossGeolocator.IsSupported
	&& await CrossGeolocator.Current.GetIsGeolocationEnabledAsync()
	&& await CrossGeolocator.Current.GetIsGeolocationAvailableAsync();
if(!geolocationAvailable)
{
	IsGeolocationAvailable = geolocationAvailable;
	return;
}
try
{
	var pos = await CrossGeolocator.Current.GetPositionAsync();
	IsGeolocationAvailable = true;
}
catch(Exception)
{
	IsGeolocationAvailable = false;
}
