### ISSUE TITLE
Droid build error after adding plugin: "The "GenerateJavaStubs" task failed unexpectedly...

### ISSUE THREAD

**Issue by wierzba3** [jamesmontemagno/GeolocatorPlugin#57]
Please fill out either the bug or feature request section and remove whatever section you are not using.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "GenerateJavaStubs" task failed unexpectedly.
System.InvalidOperationException: There can be only one type with an [Application] attribute; found: , 
   at Xamarin.Android.Tasks.ManifestDocument.CreateApplicationElement(XElement manifest, String applicationClass, List`1 subclasses, List`1 selectedWhitelistAssemblies)
   at Xamarin.Android.Tasks.ManifestDocument.Merge(List`1 subclasses, List`1 selectedWhitelistAssemblies, String applicationClass, Boolean embed, String bundledWearApplicationName, IEnumerable`1 mergedManifestDocuments)
   at Xamarin.Android.Tasks.GenerateJavaStubs.Run()
   at Xamarin.Android.Tasks.GenerateJavaStubs.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	PatrolLiveApp.Droid	C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1682	
```

## Bug 

Version Number of Plugin: 3.04
Device Tested On: 
Simulator Tested On: android xxhdpi phone emulator API 19 (but it doesn't build so this is not relevant)

### Expected Behavior
Project built before adding library.

### Actual Behavior
Project did not build after adding library.

### Steps to reproduce the Behavior'
Add plugin to portable library and android library.

## Feature Request:
Please fill in what you would like

**Comment by wierzba3** [comment]
Oops there was a duplicate MainApplication class in a separate library. Deleting the auto-generated one in the droid project solved it
